[tool.black]
line-length = 79
target-version = ['py310']
exclude = '/\.env'

[tool.flake8]
count = true
exclude = [".env"]
max-complexity = 7
max-line-length = 79
show-source = true
statistics = true

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 79
multi_line_output = 3
skip_glob = [".env","bin"]
use_parentheses = true
